# Generated by Django 6.0.4 on 2026-05-25 11:20

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_contact_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.BinaryField(blank=True, default=None, null=True, validators=[users.validators.validate_profile_image]),
        ),
    ]
