# Generated by Django 6.0.4 on 2026-06-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
