# Generated by Django 6.0.4 on 2026-04-09 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=19)),
                ('expiration_date', models.DateField()),
                ('is_expired', models.BooleanField(default=False)),
                ('cvv', models.IntegerField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('RUB', 'RUB'), ('CNY', 'CNY')], default=None, max_length=16, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='banks.bank')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
                ('payment_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='banks.paymentsystem')),
            ],
            options={
                'db_table': 'credit_cards',
                'unique_together': {('owner', 'number')},
            },
        ),
    ]
