# Generated by Django 4.1.5 on 2023-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="balance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("JPY", "JPY"),
                    ("RUB", "RUB"),
                ],
                default=None,
                max_length=16,
                null=True,
            ),
        ),
    ]
