# Generated by Django 6.0.4 on 2026-04-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('RUB', 'RUB'), ('CNY', 'CNY')], default=None, max_length=16),
        ),
    ]
