# Generated by Django 6.0.4 on 2026-05-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0002_alter_creditcard_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('RUB', 'Russian Ruble'), ('CNY', 'Chinese Yuan')], default='RUB', max_length=3),
        ),
    ]
