# Generated by Django 4.1.5 on 2023-02-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit_cards", "0003_alter_creditcard_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
    ]
