# Generated by Django 4.2.7 on 2023-11-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0007_copy_data_from_one_field_to_another'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='balance',
        ),
        migrations.RenameField(
            model_name='creditcard',
            old_name='new_balance',
            new_name='balance'
        ),
    ]
