# Generated by Django 6.0.4 on 2026-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(choices=[('central bank', 'central bank'), ('commercial bank', 'commercial bank'), ('investment bank', 'investment bank'), ('savings bank', 'savings bank'), ('mortgage bank', 'mortgage bank'), ('special bank', 'special bank')], max_length=16)),
                ('number', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, unique=True)),
                ('rates', models.JSONField()),
            ],
            options={
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('number', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'db_table': 'payment_systems',
            },
        ),
    ]
