# Generated by Django 4.1.5 on 2023-01-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("central bank", "central bank"),
                            ("commercial bank", "commercial bank"),
                            ("investment bank", "investment bank"),
                            ("savings bank", "savings bank"),
                            ("mortgage bank", "mortgage bank"),
                            ("special Bank", "special Bank"),
                        ],
                        max_length=16,
                    ),
                ),
                ("number", models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("number", models.CharField(max_length=2)),
            ],
        ),
    ]
