# Generated by Django 6.0.4 on 2026-04-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='type',
            new_name='bank_type',
        ),
    ]
