# Generated by Django 4.1.5 on 2023-01-17 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bank",
            table="banks",
        ),
        migrations.AlterModelTable(
            name="paymentsystem",
            table="payment_systems",
        ),
    ]
