# Generated by Django 6.0.4 on 2026-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_rename_type_bank_bank_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_type',
            field=models.CharField(choices=[('central', 'Central Bank'), ('commercial', 'Commercial Bank'), ('investment', 'Investment Bank'), ('savings', 'Savings Bank'), ('mortgage', 'Mortgage Bank'), ('special', 'Special Bank')], default='commercial', max_length=16),
        ),
    ]
