# Generated by Django 6.0.4 on 2026-04-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_alter_bank_bank_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_type',
            field=models.CharField(choices=[('cnt', 'Central Bank'), ('com', 'Commercial Bank'), ('inv', 'Investment Bank'), ('sav', 'Savings Bank'), ('mrg', 'Mortgage Bank'), ('spc', 'Special Bank')], default='com', max_length=16),
        ),
    ]
