# Generated by Django 4.1.5 on 2023-02-07 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banks", "0005_currency"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Currency",
        ),
    ]
