# Generated by Django 4.1.5 on 2023-02-08 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banks", "0007_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="currency",
            old_name="rate",
            new_name="rates",
        ),
    ]
