# Generated by Django 6.0.4 on 2026-04-09 09:17

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=images.models.get_upload_to)),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
