# Generated by Django 4.1.5 on 2023-01-16 09:55

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=images.models.get_upload_to)),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
