# Generated by Django 4.1.5 on 2023-01-17 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="image",
            table="images",
        ),
    ]
